language: c
complier:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp-dev valgrind clang

before_script: autoreconf -i
script: "scan-build ./configure && scan-build make && scan-build make distcheck"
