language: c
complier:
  - clang
  - gcc

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq libgmp-dev valgrind clang cppcheck

before_script:
  - ./autogen
  - cppcheck -I. --error-exitcode=1 src/*.c

script:
  - scan-build ./configure
  - scan-build make
  - scan-build make check
  - scan-build make distcheck
