language: c
complier:
  - clang
  - gcc

addons:
  apt:
    packages:
    - libgmp-dev
    - valgrind
    - clang
    - cppcheck

before_script:
  - ./autogen

script:
  - scan-build ./configure
  - scan-build make
  - scan-build make check
  - scan-build make distcheck

sudo: false
